use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Indicator configuration for strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndicatorConfig {
    /// Indicator type: ma, ema, rsi, macd, boll, volume
    pub indicator_type: String,
    /// Parameters for the indicator, e.g., {"period": 5} for MA
    pub params: HashMap<String, f64>,
    /// Optional alias to reference this indicator in conditions
    pub alias: Option<String>,
    /// Which candle field to use: close, open, high, low, volume
    #[serde(default = "default_field")]
    pub field: String,
}

fn default_field() -> String {
    "close".to_string()
}

/// Comparison operators for conditions
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ComparisonOp {
    #[serde(rename = "gt")]
    GreaterThan,
    #[serde(rename = "lt")]
    LessThan,
    #[serde(rename = "gte")]
    GreaterThanOrEqual,
    #[serde(rename = "lte")]
    LessThanOrEqual,
    #[serde(rename = "eq")]
    Equal,
    #[serde(rename = "cross_above")]
    CrossAbove,
    #[serde(rename = "cross_below")]
    CrossBelow,
}

impl ComparisonOp {
    pub fn as_str(&self) -> &'static str {
        match self {
            ComparisonOp::GreaterThan => ">",
            ComparisonOp::LessThan => "<",
            ComparisonOp::GreaterThanOrEqual => ">=",
            ComparisonOp::LessThanOrEqual => "<=",
            ComparisonOp::Equal => "==",
            ComparisonOp::CrossAbove => "cross_above",
            ComparisonOp::CrossBelow => "cross_below",
        }
    }
}

/// Signal condition for generating buy/sell signals
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalCondition {
    /// Reference to an indicator by alias
    pub indicator: String,
    /// Comparison operation
    pub comparison: ComparisonOp,
    /// What to compare against: another indicator alias or a literal value
    pub compare_with: CompareTarget,
}

/// Target for comparison
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompareTarget {
    /// Compare against another indicator's value
    Indicator(String),
    /// Compare against a literal value
    Value(f64),
}

/// Trade action configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeAction {
    /// Direction: buy or sell
    pub direction: String,
    /// Position sizing: 0.0 to 1.0 representing percentage of capital
    #[serde(default = "default_target_percent")]
    pub target_percent: f64,
}

fn default_target_percent() -> f64 {
    0.95
}

/// Complete strategy configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    /// Unique identifier
    pub id: String,
    /// Strategy name
    pub name: String,
    /// Strategy description
    pub description: String,
    /// List of indicators to calculate
    pub indicators: Vec<IndicatorConfig>,
    /// Conditions that generate buy signals
    pub conditions: Vec<ConditionGroup>,
    /// Conditions that generate sell signals (optional, uses config-defined if not set)
    #[serde(default)]
    pub sell_conditions: Option<Vec<ConditionGroup>>,
    /// What to do when buy condition is met
    pub buy_action: TradeAction,
    /// What to do when sell condition is met
    pub sell_action: TradeAction,
    /// Symbols to trade
    pub symbols: Vec<String>,
    /// Time period: 1d, 1h, 5m, 1m
    #[serde(default = "default_period")]
    pub period: String,
}

fn default_period() -> String {
    "1d".to_string()
}

/// Group of conditions with AND/OR logic
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConditionGroup {
    /// Logic operator: and, or
    #[serde(default = "default_logic")]
    pub logic: String,
    /// List of conditions in this group
    pub conditions: Vec<SignalCondition>,
}

fn default_logic() -> String {
    "and".to_string()
}

/// Signal generated by strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategySignal {
    pub timestamp: String,
    pub symbol: String,
    pub action: SignalAction,
    pub price: f64,
    pub quantity: f64,
    pub reason: String,
}

/// Signal action type
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SignalAction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
    #[serde(rename = "hold")]
    Hold,
}

impl StrategySignal {
    pub fn buy(symbol: &str, timestamp: &str, price: f64, quantity: f64, reason: &str) -> Self {
        Self {
            timestamp: timestamp.to_string(),
            symbol: symbol.to_string(),
            action: SignalAction::Buy,
            price,
            quantity,
            reason: reason.to_string(),
        }
    }

    pub fn sell(symbol: &str, timestamp: &str, price: f64, quantity: f64, reason: &str) -> Self {
        Self {
            timestamp: timestamp.to_string(),
            symbol: symbol.to_string(),
            action: SignalAction::Sell,
            price,
            quantity,
            reason: reason.to_string(),
        }
    }

    pub fn hold(symbol: &str, timestamp: &str, reason: &str) -> Self {
        Self {
            timestamp: timestamp.to_string(),
            symbol: symbol.to_string(),
            action: SignalAction::Hold,
            price: 0.0,
            quantity: 0.0,
            reason: reason.to_string(),
        }
    }
}

/// Running strategy instance state
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyInstance {
    pub instance_id: String,
    pub strategy_id: String,
    pub config: StrategyConfig,
    pub status: StrategyStatus,
    pub positions: HashMap<String, f64>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// Strategy running status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum StrategyStatus {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "error")]
    Error,
}

/// Request to start a live strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StartStrategyRequest {
    pub strategy_id: String,
    pub config: StrategyConfig,
    pub capital: Option<f64>,
}

/// Request to run backtest
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestRequest {
    pub config: StrategyConfig,
    pub symbol: String,
    pub period: Option<String>,
    pub count: Option<u32>,
    pub initial_capital: Option<f64>,
    pub commission_rate: Option<f64>,
}

/// Strategy template for the marketplace
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyTemplate {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub config: StrategyConfig,
    pub performance: TemplatePerformance,
    pub code_example: String,
}

/// Pre-computed performance metrics for templates
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplatePerformance {
    pub total_return: f64,
    pub annual_return: f64,
    pub max_drawdown: f64,
    pub sharpe_ratio: f64,
    pub win_rate: f64,
    pub total_trades: i32,
}

impl Default for TemplatePerformance {
    fn default() -> Self {
        Self {
            total_return: 0.0,
            annual_return: 0.0,
            max_drawdown: 0.0,
            sharpe_ratio: 0.0,
            win_rate: 0.0,
            total_trades: 0,
        }
    }
}
