pub mod anomaly;
pub mod news_analyzer;
pub mod hot_stocks;
pub mod backtest;
pub mod scanner;
pub mod momentum;
pub mod risk;
pub mod financial;
pub mod capital_flow;
pub mod notification;
pub mod trading;
pub mod screener;
pub mod ai_pattern;

pub use anomaly::AnomalyDetector;
pub use news_analyzer::{NewsAnalyzer, Sentiment, AnomalyPrediction};
pub use hot_stocks::HotStockRanker;
pub use backtest::BacktestEngine;
pub use scanner::MarketScanner;
pub use momentum::{MomentumStrategy, MomentumSignal};
pub use risk::{RiskManager, RiskConfig, RiskReport, TradeSignal, TradeType, TradeAction};
pub use financial::{FinancialService, FinancialData, FinancialFilter, DragonTigerService, DragonTigerData};
pub use capital_flow::{CapitalFlowService, CapitalFlow, SectorFlow, FlowAnomaly};
pub use notification::{NotificationService, AlertManager, Notification, NotificationType};
pub use trading::{TradingEngine, Broker, Order, Position, Account, FutuConfig, OrderType, Direction, OrderStatus};
pub use screener::ScreenerService;
pub use ai_pattern::{AIPatternService, PatternResult, PatternType, BreakoutDirection, TrendType, ScreenParams};
